import { config } from '@fortawesome/fontawesome-svg-core';
import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import './globals.css';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;

const font = Source_Sans_3({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`bg-stone-100 text-black dark:bg-stone-900 dark:text-white ${font.className}`}
      >
        {children}
      </body>
    </html>
  );
}
