name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Execute remote SSH commands
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: anglish.wiki
          username: appuser
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo 'yooooo waddup'
